### PR TITLE
windows: start is a cmd command, not an executable

### PR DESCRIPTION
**Pull request by oli-obk**

### CODE REVIEW

**Comment by Byron** [comment]
Thanks for your contribution !
I will write a little example to be able to actually (finally) test this and then publish a new version on crates.io.

**Comment by Byron** [comment]
I have added a binary called `open` which can be used to easily test the functionality on the various platforms. Originally I wanted to test whether it works on windows, but didn't manage to link it there. Maybe if you have time, you can give it a test-run.
Thanks and cheers

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/lWSkZWqXP8U).

*`Hacks #1 [open-rs - writing a program to open things]`*

[\thumb](https://youtu.be/lWSkZWqXP8U)

**Comment by oli-obk** [comment]
> Maybe if you have time, you can give it a test-run.

works like a charm now (both the executable and the library)

**Comment by Byron** [comment]
Great, thanks for letting me know!

**Pull request merged**
