### PR TITLE
WIP: adds with() function to open with arbitrary apps

### PR DESCRIPTION
**Pull request by hoodie**
Hi there, I quickly hacked this together, had no chance to test it on windows yet so : WIP

### CODE REVIEW

**Comment by Byron** [comment]
@hoodie It looks like the PR does not compile - please have a look at the Travis logs for the details. Once that is fixed, I am happy to cut a new release.

**Comment by hoodie** [comment]
sorry for the quick draft, the was more a suggestion on the interface then a propper solution, I'll gladly give it a go tomorrow :D

**Comment by Byron** [comment]
@hoodie Alright - I will keep this one open, and will have a look at it when some new commits come in :)!

**Comment by hoodie** [comment]
no time currently sorry, I'll have access to a windows machine again over chrismas :P

**Comment by Byron** [comment]
Closed due to inactivity :). Maybe something similar is implemented by now as well.

**Pull request closed without merging**
