### PR TITLE
Bring back Android support

### PR DESCRIPTION
**Pull request by vladimyr**
This fixes Starship's compilation under Termux.

Closes https://github.com/starship/starship/issues/2432

### CODE REVIEW

**Comment by Byron** [comment]
I am sorry for having let that slide previously, and thanks for the fix!

**Comment by Byron** [comment]
Version 1.6.0 was just released, containing the fix.

**Comment by vladimyr** [comment]
> I am sorry for having let that slide previously, and thanks for the fix!

No worries, thank you for the express release! 💯

**Comment by Byron** [comment]
And that reminds me: v1.5.1 is now yanked as well preventing others from seeing similar issues.

When seeing the new 'explicit include' style of OS' instead of going by platform my spider sense was tingling as it was a risk. 
However, the list looked so compellingly complete that I thought that "it's probably alright", maybe also driven by getting the PR out of my inbox quickly. I wish that one day I am able to pause and halt in situations like these - let's call this a post-mortem :).

All the best for 🚀!

**Comment by vladimyr** [comment]
> I wish that one day I am able to pause and halt in situations like these - let's call this a post-mortem :).

But where is the fun in that? 😂
 
> All the best for 🚀!

Thank you! ❤

**Pull request merged**
