### PR TITLE
feat: add `that_detached` and `with_detached`

### PR DESCRIPTION
**Pull request by amrbashir**
ref: https://github.com/tauri-apps/tauri/issues/6849

### CODE REVIEW

**Review by Byron — APPROVED** [review]
Sorry for the late reply and thanks for the contribution! I wonder what the difference is to a normal `Command::spawn()`, and figure it must be the `out-live your app` scenario described in the documentation.

All looks good, even though I would have loved to read why `unsafe {}` is safe with our usage. Over at `alacritty` there is also no description and I assume it's because `libc` is simply unsafe for all kinds of reasons :).

**Comment by Byron** [comment]
And [here is the new release](https://github.com/Byron/open-rs/releases/tag/v4.2.0).

**Comment by amrbashir** [comment]
> Sorry for the late reply and thanks for the contribution! I wonder what the difference is to a normal `Command::spawn()`, and figure it must be the `out-live your app` scenario described in the documentation.

Correct. This library just calls another app, for Windows it is `start`, for Linux it is `xdg-open`...etc and this apps usually assign a new process for the launched app but looks like some linux distros doesn't do that so we ensure that the new command is ran in a separate new process.

> All looks good, even though I would have loved to read why `unsafe {}` is safe with our usage. Over at `alacritty` there is also no description and I assume it's because `libc` is simply unsafe for all kinds of reasons :).

Yeah `libc` is just inherently unsafe because it calls into C APIs. The usage of `unsafe` here is actually safe because we are not using any pointers at all or doing any dark magic, we are just calling unsafe C APIs.

**Comment by amrbashir** [comment]
> And [here is the new release](https://github.com/Byron/open-rs/releases/tag/v4.2.0).

Thank you

**Pull request merged**
