### PR TITLE
Make open::that not wait on the child process on UNIX-like systems

### LINKED ISSUE #46: Open files in a non-blocking manner
My use case for this feature is quite specific. I am making a book/article organizer, and would like to be able to open the files via CLI and TUI. 

Currently, opening files like PDF prevents the program from exiting because the child process (in my case, a PDF reader `zathura`) is awaited by the parent [here](https://github.com/Byron/open-rs/blob/bf6e99cb578cd3c90eed3ff4fddd712b26982e21/src/lib.rs#L204). This would affect the future TUI of my program even more, making it unresponsive.

Ideally, I would like to have something like `open::that_and_forget`:
```rust
pub fn that_and_forget<T: AsRef<OsStr>>(path: T) -> Result {
    let path = path.as_ref();
    let open_handlers = [
        ("xdg-open", &[path] as &[_]),
        ("gio", &[OsStr::new("open"), path]),
        ("gnome-open", &[path]),
        ("kde-open", &[path]),
        ("wslview", &[&wsl_path(path)]),
    ];

    let mut unsuccessful = None;
    let mut io_error = None;

    for (command, args) in &open_handlers {
        let result = Command::new(command).args(*args).spawn();

        match result {
            Ok(_) => return Ok(()),
            Err(err) => io_error = io_error.or(Some(err)),
        }
    }

    Err(unsuccessful
        .or(io_error)
        .expect("successful cases don't get here"))
}
```
which does not wait for the child to finish. Error handling could be completely abandoned in this case, placing the burden on the end user.

I am eager to know what you think about how this could be approached, or whether this should be a part of the `open` crate at all.

### PR DESCRIPTION
**Pull request by kirusfg**
- Fixes #46 by removing stderr handling (as per @Byron's patch)

### CODE REVIEW

**Comment by Byron** [comment]
[My comment somewhat relates to this PR](https://github.com/Byron/open-rs/issues/46#issuecomment-1152890284) and I like the proposition made there. Maybe this PR can be adjusted for that or a new one can be opened?

**Comment by kirusfg** [comment]
Done. I also removed the reording of launchers, since it turns out that `xdg-open` is a shell script that detects Desktop Environments and uses their respective launchers.

**Comment by Byron** [comment]
Thanks for your help! This looks like it's the posted patch applied here, which is part of the work.

To get it done quickly I did that myself in the related PR, and will be closing this one for that reason. Thanks for the initiative to resolve the problem, it clearly was you who gave it the required 'push' :).

**Comment by kirusfg** [comment]
I am just happy that this great tool got better, despite not contributing much. Good job on your part with the timely responses and the rest!

**Pull request closed without merging**
